### ISSUE TITLE
Mac OS X: Crashes when playing sample

### ISSUE THREAD

**Issue by jkrosado** [davy7125/polyphone#101]
[video of polyphone crashing](https://youtu.be/HxB3j5YB3SL)

**Comment by nashspence** [comment]
Hey, thanks for the great tool! 

I also have this issue with Polyphone 2.2 on OSX Catalina 10.15.7. It prevents really being able to tune samples very well. When pressing the play button if in looped mode, the application will hang permanently with the sample still playing. When pressing the play button in non-looped mode, the application will hang for about 10-20 seconds and then become somewhat responsive again. 

Repro is easy enough as it happens every time you try to play any sample file using the play button. Playing samples using a MIDI keyboard seems to work as it should. Let me know if you need any more info or whatnot

**Comment by jkrosado** [comment]
i'm still waiting for a fix after nearly a year, happens on 10.15.7 and 11.1

**Comment by davy7125** [comment]
Maybe linked:
https://www.polyphone-soundfonts.com/forum/support-bug-reports/451-sample-playback-doesn-t-stop-on-mac-os-mojave
