### ISSUE TITLE
Panel and switcher Icons broken

### ISSUE THREAD

**Issue by erwan35** [davy7125/polyphone#103]
Hello,

I'm using polyphone 2.2.0 on Librazik Linux distribution.

I have noticed the icon is missing on the panel :

![panel](https://user-images.githubusercontent.com/4410119/81477229-f4125780-9216-11ea-935e-e11770ced481.png)

or the switcher :

![switcher](https://user-images.githubusercontent.com/4410119/81477233-f83e7500-9216-11ea-8ad3-aeab25c13640.png)

Thanks for the cool software.

Cheers
Erwan

**Comment by trebmuh** [comment]
(LibraZiK packager here) @davy7125 : note that the icon displays fine in the menu:

![polyphone-icon](https://user-images.githubusercontent.com/8705846/81479394-30e44b80-9223-11ea-8ad5-d8a8d6ae39f5.png)

Anything I could do on my side maybe? _(such a misplaced/forgotten icon picture installation maybe)_
