### ISSUE TITLE
PCM (.wav) files with loop markers cannot be imported 

### ISSUE THREAD

**Issue by CardboardCarl** [davy7125/polyphone#109]
A .wav file I'm trying to import has loop markers. Polyphone doesn't recognize it and mistakes it as a "Corrupted File."

I've tried using multiple different programs to open the same file and it plays as intended.

A temporary solution would be to just ignore loop markers and import the audio only. If it's possible, though, a better option would be to import the markers as well.

**Comment by davy7125** [comment]
Is it possible to provide me with this .wav file? I'm often importing such samples and the loop points are correctly read.
I'm closing this ticket for now since it's been a long time and the bug is possibly fixed but I'll reopen it if needed.
Regards
