### ISSUE TITLE
hardcoded assumption to run on little endian

### ISSUE THREAD

**Issue by mirabilos** [davy7125/polyphone#123]
`sources/core/output/sf2/outputsf2.cpp` line 326, for example:

```
  324     /////////////////////////////////////// BLOC INFO ///////////////////////////////////////
  325     fi.write("LIST", 4);
  326     fi.write((char *)&taille_info, 4);
  327     fi.write("INFO", 4);
```

(Also, WHY IS THAT FRENCH?!?!?!)

This completely breaks using this on big endian platforms (let alone PDP but pray we’re not going there).

**Comment by davy7125** [comment]
Sorry I won't be correcting this problem as no requests have been made to run Polyphone on a big-endian architecture.
Digging into the Qemu virtualization of a big-endian OS and adapting the software will probably never be a priority.
