### ISSUE TITLE
Mac OS X: FLAC/stream_decoder.h not found

### ISSUE THREAD

**Issue by matkatmusic** [davy7125/polyphone#126]
Cloned the git repo onto a blank OS X install of OS X 10.13.6.
installed Qt 5.15.0, opened the project, tried to build. 
`FLAC/stream_decoder.h` not found is the first error reported when trying to compile `samplereaderflac.cpp`

It seems your build system requirements for OS X are missing instructions to include:
- the FLAC library and subsequent header files.
- the PortAudio library and subsequent header files
- the Vorbis library and subsequent header files
- the OGG library and subsequent header files

Each of these libraries' source code repositories need to be cloned, and then their `include` folder that contains the missing header files needs to be copied to `lib_mac/include`

once these header files are added, the project will compile and run on OS X.

I'm going to guess that these header files are not included because of licensing issues.

![Screen Shot 2020-09-12 at 10 54 33 PM](https://user-images.githubusercontent.com/2929847/93011449-3cd27800-f54b-11ea-8b2c-9a9cd99e9dbb.png)

**Comment by davy7125** [comment]
I updated the "lib_mac" archive on the polyphone website.
LibFlac has been added
PortAudio has been updated also
