### ISSUE TITLE
Conversion to sfz causes floating point exception.

### ISSUE THREAD

**Issue by joseluisquiroga** [davy7125/polyphone#127]
The bug is when converting to sfz either by the interface or by command line.

It fails for the following files:

https://github.com/joseluisquiroga/bug_1_polyphone

When running 

polyphone -3 -i <the_file>

**Comment by mirabilos** [comment]
Confirmed even for the Debian package, which uses the latest git snapshot _and_ `-ffloat-store` for normalised FPU precision.
