### ISSUE TITLE
Sample playback issue

### ISSUE THREAD

**Issue by Yoshimaster96** [davy7125/polyphone#129]
Sometimes a sample's "Link" setting is not set properly for no discernible reason (such as with the Fluid R3 GM soundfont where it's often set to "Gun"). This affects playback and WAV export by layering the linked sound on top of the actual sample, which is probably not desired.

**Comment by davy7125** [comment]
I downloaded the Fluid R3 GM soundfont and all samples seem to be correctly linked.
Maybe errors have been introduced when you edited this soundfont? I would need the description of what happened if this is the case.
I'm closing this ticket for now.
