### ISSUE TITLE
Importing 32-bit float .wav file at peak level causes very ugly clicking noise

### ISSUE THREAD

**Issue by ipatix** [davy7125/polyphone#131]
This bug, which is causing very nasty sounds, is very easy to reproduce:

- open Audacity or similar, generate a sine wave with peak at 0dBFS
- save file as 32-float .wav
- import in polyphone
- playback and hear not simply clipping artifacts, but it seems like some type of overflow error that causes very nasty clicking noise

This is not a playback problem but an actual sample data problem. When I export the sine wave back to Audacity, you can see the following difference:

![glitch](https://user-images.githubusercontent.com/8502545/101100113-3e4d9280-35c6-11eb-8658-22a35a9ebbbe.png)

So most likely the maxmimum positive float value is improperly converted to int and causing an overflow.

**Comment by davy7125** [comment]
I generated a sine wave as you described and then exported it as 32-float .wav (among other options).
The bug cannot be reproduced, maybe it's been already fixed.

**Comment by ipatix** [comment]
Well, I haven't been able to try it again, but my instructions theoretically might not be sufficient to reproduce this problem since depeding on the caluclation accuracy a sine wave might not contain a critical value (like in the imagine not all cycles have this phenomenon).

Since I usually do not build Polyphone from source, which version should I try to see if this problem still exists?

**Comment by davy7125** [comment]
Fixed!
I reproduced the bug with an amplified sample (using Audacity and allowing saturation). IEEE float wav files possibly contain values exceeding 1.0 and I didn't take it into account.
