### ISSUE TITLE
Build not reproducible (plus typographic nitpick)

### ISSUE THREAD

**Issue by mirabilos** [davy7125/polyphone#134]
The build process hardcodes the current year:

    sources/dialogs/dialog_about.cpp:    QString annee = "2013 -" + QString::number(QDate::currentDate().year());

(it’s also wrong, it must be `"2013 - " +` or `"2013-" +` and ideally not `-` but `–`)

Given that copyright is only triggert by relevant changes (threshold of originality, creativity requirement) it’s best to only ever update the copyright year manually.

**Comment by davy7125** [comment]
You are right!
It's currently configured to show "2013 - 2022", I hope you will not open a ticket for this :-)

By the way, I don't know the conditions that are required to add a name in the contributor section but you are helping quite a lot so if you want I can mention you in the contributors

**Comment by mirabilos** [comment]
No, that’s fine ;-)

@ contributors list: sure, if you want, add `mirabilos` with `tg` at `debian.org` as address. Merci!
