### ISSUE TITLE
Changing font size(s)

### ISSUE THREAD

**Issue by dromer** [davy7125/polyphone#135]
The current font sizes are about a factor 2-3 too big for my liking and I'd like to be able to change them.

It would be nice if there are some extra Interface settings to modify these.

**Comment by davy7125** [comment]
2-3 too big is weird since the fonts should be based on the system font.
Could you please provide a screenshot with Polyphone and the file browser for example, to see the difference?
I'm closing the ticket since it's been a long time but re-open it if I have more information.
