### ISSUE TITLE
I can't get into the website.

### ISSUE THREAD

**Issue by galactic649** [davy7125/polyphone#137]
Whenever I try it says getting into it I get an error message saying

"This page isn't working.
www.polyphone-soundfonts.com redirected you too many times
Try clearing your cookies."

I opened it in incognito (because I didn't feel like clearing my cookies), and I still got the same error message. Both Chrome and Safari do this.

**Comment by 0xCAPTAINMALWARE** [comment]
I am having a similar issue, but not exact. I can get into the website, but when I try to download some files (Windows32 & Windows64), It redirects me to the same page with an error that reads:

"Error"
"File does not exist"

Anyone got a lead on what's causing these issues?
![Screenshot 2021-02-04 191018](https://user-images.githubusercontent.com/77933654/106975723-a894c780-671c-11eb-9e6d-081458d71735.png)

**Comment by davy7125** [comment]
I think it was a temporary issue. The website appears to be OK now.
