### ISSUE TITLE
editor/tree/treeitemdelegate.cpp:144:18:

### ISSUE THREAD

**Issue by Downsend** [davy7125/polyphone#138]
g++ -c -pipe -std=c++11 -O2 -O2 -fPIC -std=gnu++11 -pthread -pthread -Wall -Wextra -D_REENTRANT -fPIC -DUSE_LOCAL_QCUSTOMPLOT -DUSE_LOCAL_QCUSTOMPLOT -DSOFT_VERSION=\"2.1.0\" -DIDENTIFIER=\"DEVEL\" -D__LINUX_ALSASEQ__ -DSFTOOLS_NOXML -D__LITTLE_ENDIAN__ -D__UNIX_JACK__ -D__LINUX_ALSA__ -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I/usr/include/jack -Ilib/flac -I/usr/include/stk -Ilib/qcustomplot -Imainwindow -Idialogs -Icontext -Icontext/interface -Ieditor -Ieditor/graphics -Ieditor/modulator -Ieditor/overview -Ieditor/tools -Ieditor/widgets -Ieditor/tree -Iqcustomplot -Iresources -Icore -Icore/input -Icore/output -Icore/model -Icore/sample -Icore/types -Iclavier -Isound_engine -Isound_engine/elements -Ilib/sf3 -Irepository -Irepository/browser -Irepository/daily -Irepository/widgets -Irepository/user -Irepository/soundfont -Irepository/soundfont/viewer -Irepository/soundfont/editor -I. -Ilib/sfarklib -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/rtmidi -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -Igenerated_files -Igenerated_files -I/usr/lib64/qt5/mkspecs/linux-g++ -o generated_files/treeitem.o core/model/treeitem.cpp
In file included from core/types/basetypes.h:31,
                 from editor/tree/treeview.h:29,
                 from editor/tree/treeitemdelegate.cpp:27:
core/types/attribute.h: In constructor ‘AttributeValue::AttributeValue()’:
core/types/attribute.h:190:62: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘union AttributeValue’; use assignment or value-initialization instead [-Wclass-memaccess]
  190 |     AttributeValue() { memset(this, 0, sizeof(AttributeValue)); }
      |                                                              ^
core/types/attribute.h:172:7: note: ‘union AttributeValue’ declared here
  172 | union AttributeValue
      |       ^~~~~~~~~~~~~~
editor/tree/treeitemdelegate.cpp: In member function ‘void TreeItemDelegate::drawRoot(QPainter*, const QStyleOptionViewItem&, const QModelIndex&, bool) const’:
editor/tree/treeitemdelegate.cpp:144:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
  144 |     QPainterPath path;
###############################################################################

Looks like it could be a typo, and I'm not that fluent or brave enough to try and fix it myself. Could be QPainterPath clipPath() ??

**Comment by davy7125** [comment]
This line was probably missing in file "treeitemdelegate.cpp" at the time you built Polyphone:
`#include <QPainterPath>` 

Now it is included
