### ISSUE TITLE
Exporting to SF3 Creates Pops in Audio Files

### ISSUE THREAD

**Issue by WrillicR** [davy7125/polyphone#143]
Using Polyphone 2.2, I exported my piano.sf2 as an SF3 and found pops and clicks in the samples that were not originally there and are quite noticeable. This happened at Medium, High, and Low export quality. Most of the clicks were in the midrange notes (G2ish-A5ish). Polyphone is my only way of converting SF2's to SF3's at the moment. I can send the SF2 that I used if need be.

**Comment by mirabilos** [comment]
Why can’t you use [MuseScore’s `sf3convert`](https://github.com/musescore/sftools) (packaged as [`sf3convert`](https://packages.debian.org/buster/sf3convert) in Debian)?

**Comment by ziyamete** [comment]
Select all of your samples and reduce their attenuation to around 90% ~ 95%. Samples with a decibel level higher than this (eg 98%) may experience problems converting to sf3 format (such as dropout).

**Comment by davy7125** [comment]
This is not a bug but inherent to the lossy OGG compression that ruins the existing loops.
MuseScore sf3convert will do the same. Bad design.
