### ISSUE TITLE
2.2.0: Segfault upon opening of polyphone

### ISSUE THREAD

**Issue by dvzrv** [davy7125/polyphone#144]
Hi! The 2.2.0 release (which is still the current release on Arch Linux) is crashing upon start: https://bugs.archlinux.org/task/71420

It would be really great if you could release a new version of the application, as I have built current HEAD (https://github.com/davy7125/polyphone/commit/75a5e88d361f6e141dbad17673e1fc25291cae10) which at least lets me open the application (but it crashes upon exit and kills my jack and crashes the driver).

I guess for non jack users the latter outcome is still better than not being able to use the application at all though.

**Comment by dvzrv** [comment]
The crash upon exit is fairly severe itself and is tracked in https://github.com/davy7125/polyphone/issues/112.

**Comment by sudofox** [comment]
Bump for this? Running Arch and I get the same issue.
