### ISSUE TITLE
Polyphone installer on Windows does not supply the Visual C/C++ 2013 redistributables (msvcr120.dll)

### ISSUE THREAD

**Issue by zeta0134** [davy7125/polyphone#145]
On a fresh install of Polyphone 2.2, on Windows 10, launching the program produced a warning message (which I neglected to screenshot, so sorry!) which complains about a missing "msvcr120.dll" file. This warning repeats 4 times, and then the program exits.

This file is provided by the following package, which the user currently needs to discover and install manually:

https://www.microsoft.com/en-us/download/details.aspx?id=40784

Since Polyphone is already using an install flow on Windows, logically it would seem to make sense to include this redistributable as part of the installer. If license terms do not permit this (perhaps the proprietary redistributable somehow conflicts with GPL?) then instead the download / release pages should mention this requirement for Windows users.

**Comment by davy7125** [comment]
Thank you for the notice. I'll build a new version of Polyphone next month and I'll take care of this
All dependencies should be included in the installer

**Comment by davy7125** [comment]
Installers for version 2.2 are now fixed
