### ISSUE TITLE
soundfonts exporting very quiet

### ISSUE THREAD

**Issue by envypaw** [davy7125/polyphone#147]
for some reason, when i export my soundfonts, they will be very quiet, and i cant find a way to fix them.

**Comment by junaayd123** [comment]
I agree… soundfonts should be the original sample loudness and db.

**Comment by davy7125** [comment]
What kind of file are you loading? sfz import followed by a sf2 export?

**Comment by davy7125** [comment]
I'll re-open this ticket if more details are provided

**Comment by NeverNoodle** [comment]
I'm making sf2 files with .wav files i export out of audacity, and then it keeps coming out really quiet, sometimes restarting my pc and remaking it will work but it doesnt always work. @davy7125

**Comment by junaayd123** [comment]
Maybe something happened in newer releases of Polyphone? I found some old soundfonts playing at the original sample velocity, but when going to newer soundfonts, the db completely went down... I tried making loud soundfonts, and they became quiet.

**Comment by davy7125** [comment]
I don't know if this is linked but in the preferences, section "sound", there is an option to change the behavior of the parameter "velocity => cutoff filter". There is an explanation here:
https://www.polyphone-soundfonts.com/forum/support-bug-reports/401-v2-1-issues-with-default-velocity-to-fc-mod

If this is possible I'd like to have a soundfont along with its exported soundfont, so that I can investigate.

**Comment by junaayd123** [comment]
I played around with all the volume things or whatever is related, and then suddenly the original sample became quieter than the soundfont! I can’t for some reason send the soundfont, but I can share an MP4 on the differences between the sample and the soundfont later.

**Comment by sound8** [comment]
Thank You so much for this great program.

I have experienced this as well.
When you export any SFZ to Soundfont, the exported soundfont version ends up with a lower volume than the original SFZ.

Tried many SFZ exports and all end up with the same lower volume soundfont result, so it does not seem to be a specific code that only some SFZ instruments have that is causing this.

I have read something along the line that SFZ has a different default attenuation (volume) than Soundfonts, so when you do the convert it appears to result in the Soundfonts default attenuation which is a lower value.

The same thing unfortunately occurs when trying to export GrandOrgue instruments to Soundfont, you get the same lower volume soundfont result as well.

Only available option in Polyphone that I know of is that you have to manually change the "attenuation" value before performing the export which is tedious if want to convert many items.
I have a possible solution for this I will create a new post for and link it to this one.

Hopefully there is a solution for something like this, would imagine this is a pretty important issue as it hinders one of Polyphones two main functions(to create instruments and to convert them).

Thank You again for creating such an amazing program.

**Comment by sound8** [comment]
One more thing to mention that may help to figure this out.
Not sure why but, if you load the orignal SFZ instrument side by side in Polyphone with the exported Soundfont the volumes appear to be the same?  Which might be why you are not noticing a difference in volume.

It is when you load them in other programs that you notice the difference.
Have to use a player / sampler that can load both SFZ and Soundfont to accurately test.
So for example the VST called RGC Audio SFZ can load both.
Can't remember the name of it but I also tested this out in the past with a different VST sampler that was able to load both as well and same result of Soundfont being lower volume.

Anyways hopes this helps

**Comment by sound8** [comment]
As mentioned in my other post, is this the official github page for Polyphone, seems strange that no responses have been made to any of my posts?  Not even any new posts added by other users?

Used a couple different sfz instruments to test out this theory.
Of course the one I was going to reference, I can no longer find site.
It was from a company called Soundbytes, they used to have a free sfz called krumhorn which was a nice simple sfz to use to test out this issue but unfortunately cannot find online at the moment to link it here.

As mentioned above, all other programs that can load both sf2 and sfz seem to experiences this difference in volume, the only one that does not is Polyphone itself.  Does anyone know if Polyphone has some kind of gain matching built in, that makes the output of both sf2 and sfz the same?

Has anyone else tried anything out?

I made an issue post 176 which is a possible solution, if anyone is interested?

**Comment by envypaw** [comment]
closing this since it's dead
