### ISSUE TITLE
Sound font not looping

### ISSUE THREAD

**Issue by junaayd123** [davy7125/polyphone#148]
Whenever I try to loop a sample, it doesn’t loop! Please fix this! It affects how I make soundfonts.

**Comment by davy7125** [comment]
Please bring more information so that it is possible to reproduce the bug, including the sample that doesn't want to be looped.

**Comment by junaayd123** [comment]
ALL samples. So if I loop a sample in the sample editor, it loops, but in the virtual keyboard, in sample, instrument, or preset editor, it will not loop. I exported it and put it in some soundfont players, and the loop isn't working, either!

**Comment by davy7125** [comment]
Using the keyboard at the sample level will not loop the sample. Using the button "play" will do the trick.
At the instrument level you need to enable the loop in the field "loop playback"
https://www.polyphone-soundfonts.com/documentation/en/manual/soundfont-editor/editing-pages/instrument-editor#doc_table

For other questions regarding the soundfont editing, it would be better to use the forum
https://www.polyphone-soundfonts.com/forum
