### ISSUE TITLE
Virtual keyboard not working before exporting an instrument

### ISSUE THREAD

**Issue by junaayd123** [davy7125/polyphone#151]
I don't know if this has been patched or not, but when clicking on virtual keyboard, it doesnt pop up. This is before the project is saved as a soundfont. I don't know if this is an issue or if this is intentional, but if this is intentional, I would suggest making it possible to open the virtual keyboard before exporting to test it. Thanks!

**Comment by junaayd123** [comment]
Wait... does the virtual keyboard run from the exported soundfont or from polyphone?

**Comment by davy7125** [comment]
Fixed in commit 91dc3479835744fd5028448ec469019a891f8a45
You are right, the dialog containing the keyboard should open when we click on the button.
If you want to run an exported soundfont, you just need to open it and play with it.
