### ISSUE TITLE
Polyphone suddenly freezing when playing looped samples.

### ISSUE THREAD

**Issue by junaayd123** [davy7125/polyphone#152]
I see this problem with looped samples. I play a looped sample, then Polyphone suddenly freezes, the sample still playing. I then have to force quit Polyphone. This doesn't happen all the time, it only happens about 85-90% of the time.

**Comment by davy7125** [comment]
Are you running Polyphone on macOS or Windows?

**Comment by junaayd123** [comment]
macOS. I don’t know about Windows, because of windows 11 cross compatibility… error related stuff.

**Comment by junaayd123** [comment]
https://user-images.githubusercontent.com/69608246/152654377-ce3a95a9-d538-4639-9956-35fa8d243d12.mp4

**Comment by junaayd123** [comment]
never mind hold on
