### ISSUE TITLE
Add support for m4a and/or mp3 files by converting to wav

### ISSUE THREAD

**Issue by junaayd123** [davy7125/polyphone#154]

**Comment by davy7125** [comment]
Are you speaking of the offsets, available in the instrument section?
https://www.polyphone-soundfonts.com/documentation/en/manual/soundfont-editor/editing-pages/instrument-editor#doc_table

**Comment by davy7125** [comment]
mp3 => will be done in ticket #64 (use of libsndfile)
m4a => will be done when libsndfile can read them and from what I can read,
