### ISSUE TITLE
The application was unable to start correctly (0xc000####). (win32)

### ISSUE THREAD

**Issue by eeshvardasikcm** [davy7125/polyphone#156]
I'm running Windows 10 with all security and feature updates current. 

Traditional Windows crash dialog with ok button.

Tried running in compatibility mode. Same result.

I'm not going to all to run as administrator.

**Comment by junaayd123** [comment]
hmm... for me all I had to do was click Windows, run the installer, and then click Polyphone... did you use the wrong bit number installer?

**Comment by eeshvardasikcm** [comment]
I don't have a bit number installer. I don't know what a bit number
installer is?

**Comment by junaayd123** [comment]
So if you have a 32 bit computer put in 32 bit installer, if you have a 64 bit computer, download the 64 bit installer.

**Comment by eeshvardasikcm** [comment]
i have a 64 bit. tried using Windows app compatibility for the 32 after 64
didn't install. has worked once or twice with different apps in the past.
not a very reliable solution to use windows app compatibility.

**Comment by eeshvardasikcm** [comment]
okay, because I have a 64 bit machine, maybe I'm not the best to ask about issues on the 32 bit install.

**Comment by eeshvardasikcm** [comment]
did that. i can try again later.
