### ISSUE TITLE
Windows Defender Smart Screen prevents loading (win64)

### ISSUE THREAD

**Issue by eeshvardasikcm** [davy7125/polyphone#157]
Smart Screen considers this Windows executable file to be unrecognized from my machine.

I'm not going to disable Smart Screen.

Possibly the developer can register this app on Windows Defender?

Maybe the other tens of thousands of downloaders are not running Smart Screen?

**Comment by davy7125** [comment]
I cannot fix this on my side, please tell Bill Gates that I'm not a virus!

Disabling Windows Defender is of course not option but you should still be able to install Polyphone: choose "Run anyway" or something like that. If the option is not available you should see how to enable it with your version of Windows.

**Comment by eeshvardasikcm** [comment]
I am sorry about Windows inability to recognize your software. Just to
clarify, Windows is claiming "Unknown Publisher".

Maybe there's some form you could fill out and put the name of the
publisher when you generate your executable files and Windows maybe will
not throw a fuss with Smart Screen. I am sorry I cannot disable Smart
Screen. Not going to reduce my security when many other apps pass Smart
Screen.

You are free to close the issue as you are the owner of the repository.

If some others were capable of "running anyway" then they may feel free to
do so.

 Thanks for your time and consideration.

 Thanks for your participation with Sound Font format files.

**Comment by davy7125** [comment]
Oh yes now I see the problem. To solve it I need to sign the installer as described here for example:
https://revolution.screenstepslive.com/s/revolution/m/10695/l/563371-signing-installers-you-create-with-inno-setup

But the certificate is not free and I don't want to pay for that.
