### ISSUE TITLE
Random Crash when playing too many time of notes

### ISSUE THREAD

**Issue by LoveBodhi** [davy7125/polyphone#160]
![Random Crash](https://user-images.githubusercontent.com/37089530/158935634-4f6c9408-ab61-467a-90b2-70ee1b0b13f6.png)

**Comment by davy7125** [comment]
I fixed a crash when reading an instrument with an exclusive class specified (or a preset using such an instrument). Is it your case?

**Comment by LoveBodhi** [comment]
Too many instrument layers, so eats CPU usage.

**Comment by LoveBodhi** [comment]
![Error 1](https://user-images.githubusercontent.com/37089530/161260153-d0f09b58-cd7f-42cb-b50c-83383a188ab5.png)

When attempt to play too many times of notes for multiple instrument layers, will result in this crash!

**Comment by davy7125** [comment]
I'm closing this ticket since the code has been updated since version 2.3
Version 2.4 is soon available
