### ISSUE TITLE
polyphone freezing when playing a sample (crash)

### ISSUE THREAD

**Issue by junaayd123** [davy7125/polyphone#161]
I had to close the other issue because of something... I don't really know what happened. But anyways, here is the recording

**Comment by junaayd123** [comment]
Wait... its not uploading. Anyways, without the recording, please fix this bug

**Comment by B00ie23** [comment]
I've had the app crash on windows when attempting to play certain drum samples via the virtual keyboard on the instruments and presets tab. This crash doesn't occur on the sample preview.

https://user-images.githubusercontent.com/45867359/159588715-b00b56a7-f2f2-499e-97a7-48f8ab80816c.mp4

Here are the steps from the clip;
1. Open any Soundfont (preferably ones with drums.)
2. Go to any drum instrument/preset.
3. Open the virtual keyboard and slowly press left or right starting from either end.
4. One of the instrument samples should cause the app to crash.

In my case; I opened Arachno and navigated to it's Room Drums, and attempted to play key 46.

Pre-Edit: Further testing revealed that anything with an Exclusive Class value set to 1 or higher causes the app crash. [This bug has already been confirmed on Polyphone's forums.](https://www.polyphone-soundfonts.com/forum/support-bug-reports/684-polyphone-2-3-crashes-if-exclusive-class-is-used)

**Comment by junaayd123** [comment]
yeah. for me the crash happens anytime anything I do on polyphone happens to do with a sample. Mostly playing it.

**Comment by junaayd123** [comment]
IMPORTANT: THIS HAPPENS IN THE MAC VERSION.

**Comment by junaayd123** [comment]
Alright, this is fixed.
