### ISSUE TITLE
Add a way to record the INPUT of a mic or something.

### ISSUE THREAD

**Issue by junaayd123** [davy7125/polyphone#165]
Lemme restate my request.
I’m asking for a feature to record the _input_. Not the output. Like a mic, and not playing an instrument through Polyphone. Thanks!

**Comment by fp22june** [comment]
click the mic icon on top right?
https://www.polyphone-soundfonts.com/documentation/en/manual/soundfont-editor/index

**Comment by junaayd123** [comment]
no, that records the output, im pretty sure.

**Comment by davy7125** [comment]
This new function, while convenient, would be out of the scope of a soundfont editor. The sample preparation should be left to other specialized software: the few signal processing functions within Polyphone will not be enough to [remove the noise](https://www.youtube.com/watch?v=MrvzHsSG2Ww) for instance.

If a simple recording is required, you can use [free software](https://listoffreeware.com/free-open-source-audio-recorder-software-windows/) or even online services.
