### ISSUE TITLE
Key range 0 to 127 but MidiNote No. 0 is not mapped

### ISSUE THREAD

**Issue by Vasa2010** [davy7125/polyphone#167]
Key range 0 to 127 but MidiNote No. 0 is not mapped
<img width="1102" alt="Screenshot 2022-06-13 at 23 00 13" src="https://user-images.githubusercontent.com/2933755/173444677-eb9cc004-903d-4329-a192-3c8407c5709a.png">

importing sfz with:
<img width="694" alt="Screenshot 2022-06-13 at 23 02 29" src="https://user-images.githubusercontent.com/2933755/173444984-bd02ce91-d7db-456b-a328-b8bc7319dc64.png">

even if you apply the transpose from polyphone the MidiNote Number 0 will not play any sample
<img width="463" alt="Screenshot 2022-06-13 at 23 05 06" src="https://user-images.githubusercontent.com/2933755/173445333-f4a356de-d547-41bc-9b9a-0a51ff323bd6.png">

**Comment by davy7125** [comment]
If I understand correctly, you tried to import an sfz file including a wav file mapped to key 0, and it didn't appear in Polyphone after the importation?

I made a try with this sfz for example and I cannot reproduce the bug:
[chamade.zip](https://github.com/davy7125/polyphone/files/14812833/chamade.zip)

The samples are correctly imported:
![Capture d’écran du 2024-03-30 18-47-09](https://github.com/davy7125/polyphone/assets/11807895/d7e084bb-4bef-4239-aa8e-5b4b850e012e)

**Comment by Vasa2010** [comment]
Hi Davy !! we can try to speak by skype or zoom
I am working in a new project and after I will go back to SFZ/2 application
player




------------------------------
*www.vasapolli.net* <http://www.vasapolli.net>


*Swiss Mobile : 0041 (0)78 816 7202*
*Bulgarian Mobile: 00359 87 795 3091*
*Italian Mobile : 0039 339 4544 791*


Skype: *pierluigi_vasapolli*


Il giorno sab 30 mar 2024 alle ore 18:50 Davy Triponney <
***@***.***> ha scritto:
