### ISSUE TITLE
Very unresponsive on Windows, stalls a lot

### ISSUE THREAD

**Issue by ciacob** [davy7125/polyphone#169]
Version 2.3.1 (latest binary found on https://www.polyphone-soundfonts.com/) is extremely unresponsive on Windows 10. Try it for your self, load this soundfont: https://ftp.osuosl.org/pub/musescore/soundfont/MuseScore_General/MuseScore_General.sf2.

Older versions used to be snapy, but 2.2 (the only one other binary that is available on your site) do not even start anymore.

What happened?

Reach me at claudius.iacob@gmail.com

Thank you.

**Comment by davy7125** [comment]
Polyphone 2.4 is avaible (beta version for now).
Please reopen if it is still slow
