### ISSUE TITLE
there is no install target?

### ISSUE THREAD

**Issue by dvzrv** [davy7125/polyphone#17]
I'm currently trying to package this software for Arch Linux' [community] repository.
However, there is no install target when doing:

```
qmake
make
make install
```

**Comment by dvzrv** [comment]
@davy7125 are you actually reading these issues?

**Comment by davy7125** [comment]
Sorry for the delay. Those lines, if you have the correct dependencies installed on your system, should be enough:
`qmke && make`

If you need more documentation you can take a look at
https://www.polyphone-soundfonts.com/en/documentation/development

**Comment by dvzrv** [comment]
Thanks for the reply!
Well, this only builds the executable.
Your make system should be able to install the executable via `make install` to `$PREFIX/bin` (defaulting to `/usr/local`, overridable by setting PREFIX).
Instead of hardcoding `RELEASE` as output directory, this should allow setting up the destination by overriding with `DESTDIR`: e.g. install the executable to `$DESTDIR/$PREFIX/bin`.
This is otherwise an additional manual step and breaks with established defaults.

**Comment by davy7125** [comment]
Ok I see. The .pro file, used by qmake and generating the makefile, can be modified. According to this [page](https://stackoverflow.com/questions/7106442/qt-project-files-and-prefix-variable) we can use the following:
```
isEmpty(PREFIX) {
 PREFIX = /usr/local
}
TARGET = polyphone
TARGET.path = $$PREFIX/
```
Instead of just using
`TARGET = polyphone`

Then, add an option to qmake:
`qmake PREFIX=/your/custom/path`

We may also have to remove
```
CONFIG(release, debug|release) {
    DESTDIR = RELEASE
    OBJECTS_DIR = RELEASE/.obj
    MOC_DIR = RELEASE/.moc
    RCC_DIR = RELEASE/.rcc
    UI_DIR = RELEASE/.ui
}
CONFIG(debug, debug|release) {
    DESTDIR = DEBUG
    OBJECTS_DIR = DEBUG/.obj
    MOC_DIR = DEBUG/.moc
    RCC_DIR = DEBUG/.rcc
    UI_DIR = DEBUG/.ui
}
```
