### ISSUE TITLE
Blue samples boxes do not line up with grid lines

### ISSUE THREAD

**Issue by sound8** [davy7125/polyphone#172]
Noticed in the grid section (where you can drag in samples and they display as adjustable blue boxes) that the blue boxes do not line up with grid lines (for either horizontal grid lines or vertical grid lines).
Vertical Grid Lines  =  the blue boxes end up with a grid line in the center of the blue note box
Horizontal Grid Lines  =  the tops and bottoms of the blue adjustable boxes cannot snap to the horizontal grid lines they can only snap above or below them.

Hopefully this makes sense.

**Comment by davy7125** [comment]
The goal of the lines was to point out specific keys or velocities in the grid and they were drawn in the center of those keys or velocities. What you described is thus normal.

However, for clarity, the lines are now replaced with rows and columns.

![Capture d’écran du 2024-03-30 18-27-08](https://github.com/davy7125/polyphone/assets/11807895/907f0089-bba6-4b32-9948-d40308aa2926)
