### ISSUE TITLE
GrandOrgue - File Association & Command Line Export

### ISSUE THREAD

**Issue by sound8** [davy7125/polyphone#174]
**File Association**
In Windows OS, Polyphone allows you to set the "Open With" (File Association) to SF2 and SFZ files.
So in Windows File Explorer when SF2 or SFZ files are selected and you hit enter key they open in Polyphone.
GrandOrgue files however are not able to associate to Polyphone so this option is not available.
Would it be possible to add the ability to set Polyphone to associate with GrandOrgue files?

**Command Line Export**
Mentioned this in my post here #173
The main reason for the request above (although probably not the reason it does not work) is that when you try to convert GrandOrgue to Soundfont with the Command Line Export option, GrandOrgue instruments are not recognized in it.

As mentioned they may be two separate issues, file association is probably not the reason for the command line not being able to perform this task.

Thank You for your help

**Comment by davy7125** [comment]
I'll also add in the installer the link with ".organ" files
