### ISSUE TITLE
Adding virtual keyboard graphic to bottom of note grid

### ISSUE THREAD

**Issue by sound8** [davy7125/polyphone#175]
Just an idea,
Most sampler / instrument creating programs show a virtual keyboard graphic at the bottom of note grid.
Might be nice to have option to show / hide a virtual keyboard graphic so users can see / align notes (blue boxes) to keyboard graphic below.  Can give user a visual of where notes are being laid out in regards to a piano keyboard layout.
Was just thinking about it because your amazing programming already contains the ablilty for the grid to adjust in height when Polyphone program window height is adjusted, so adding a keyboard might work well with this.

Sorry know this is more of a feature request, but this does kind of go in line with items I mention in this post #172.
The vertical grid lines are currently in middle of note boxes, but if keyboard added the vertical grid lines would be shifted left or right a slight amount to align with the graphic of keyboard keys edge.
If that makes sense, sorry kind of tricky to explain.

Adding a docked keyboard at bottom could also be nice because then user can also use mouse to hit the key on the virtual keyboard to test how the notes sound.

Thank You for all your help.

**Comment by davy7125** [comment]
Finally I prefer keeping the interface minimal.
Every "C" is visible so that we can distinguish every octave. Then, it is possible to listen to a sound with the help of the mouse middle button.
If needed, a keyboard can be opened in a modal window
