### ISSUE TITLE
qcustomplot 2.1 compatibility

### ISSUE THREAD

**Issue by mirabilos** [davy7125/polyphone#178]
Hi,

the Debian maintainer of qcustomplot approached me about transitioning Polyphone to the [new version 2.1](https://packages.debian.org/experimental/libqcustomplot-dev) of it.

The patch needed for this is minimal, it basically changes `-lqcustomplot` to `-lQCustomPlot` (he verified that it at least built fine with just this change). We probably should support both and have the `.pro` file check which one to use, but my qmake skills are basically nōnexistent.

However, I need to test this. Where is this actually used in Polyphone and how can I test that nothing breaks?

**Comment by rikmills** [comment]
Polyphone now marked for autoremoval from Debian on 13th December. Ubuntu likely to follow.

https://tracker.debian.org/pkg/polyphone

**Comment by mirabilos** [comment]
Rik dixit:

>Polyphone now marked for autoremoval from Debian on 13th December.

Yeah, I’ll need to be able to determine whether it works with the
new version of the library, so I’m waiting for developer input here.

**Comment by mirabilos** [comment]
I’ve now uploaded a hack to Debian to avoid it getting removed. It will now build with v2.1 but not v2.0 of the library, so the patch is not upstreamable as-is but someone who knows qmake can easily produce something suitable.

I’ve also not received any response regarding how to test whether the change will still result in a good application. Someone™ should install `polyphone (= 2.2.0.20210109+dfsg1-3)` from Debian unstable once it’s built and test that.

**Comment by davy7125** [comment]
No more qcustomplot
