### ISSUE TITLE
xdg integration

### ISSUE THREAD

**Issue by dvzrv** [davy7125/polyphone#18]
For starting this software in xdg desktop file aware Linux environments, it would be immensly helpful to provide one in this repository and install it using the install target.

In the Arch Linux User Repository (AUR) an example can be found:
https://aur.archlinux.org/cgit/aur.git/tree/polyphone.desktop?h=polyphone

**Comment by davy7125** [comment]
This file is provided in deployment/debian
https://github.com/davy7125/polyphone/blob/master/deployment/debian/polyphone.desktop
It is here since I'm using Debian for the developments and this is quite convenient to me. I update this file (along with polyphone.sharedmimeinfo) when it's needed.
