### ISSUE TITLE
Is there a way to edit soundfonts from cli ? 

### ISSUE THREAD

**Issue by MercierCorentin** [davy7125/polyphone#181]
I'm using soundfonts in a web app so I want to dl only the instruments wanted by my users.

I there a way to seperate each preset into a diffrent sf2 file ? 

Thanks a lot for this tool !

**Comment by MercierCorentin** [comment]
Found this: https://github.com/schnitzeltony/soundfont-cmdline-tools for my use case

**Comment by davy7125** [comment]
Currently, Polyphone command lines only allows conversions between formats:
https://www.polyphone.io/en/documentation/manual/annexes/command-line
More elaborate features are not planned
