### ISSUE TITLE
modulator targeting sample offset doesn't play in Polyphone

### ISSUE THREAD

**Issue by mrbumpy409** [davy7125/polyphone#182]
I thought I had reported this bug a while back on the forum already, but I couldn't find it, so I am reporting it here.

Any modulator targeting sample offset doesn't play in Polyphone, but does work correctly in players such as FluidSynth.

## Steps to Reproduce

1. Download and open the following SoundFont in Polyphone: [sample-offset-test.zip](https://github.com/davy7125/polyphone/files/14575298/sample-offset-test.zip)
2. Play each of the presets, using different velocities. Each preset uses a **velocity→sample start offset** modulator at the instrument level so that the amount of sample offset changes with velocity. This should change the sound of the note start, making it brighter at higher velocities.

## Result

Polyphone ignores the **velocity→sample start offset** modulator, so no change to tone is heard when playing different velocities.

## Expected Result

Notes should start brighter at higher velocites. To compare, Fluidsynth and current BASSMIDI both play this SoundFont correctly.

**Comment by davy7125** [comment]
Again, thank you for this one

**Comment by mrbumpy409** [comment]
Thank *you* good sir for the fixes! I have successfully compiled current master after adjusting the instructions for Qt6 (fortunately, I am on KDE neon with updated Qt6 libraries), and I can verify the issue is indeed resolved.

**Comment by coderofsalvation** [comment]
awesome, thanks for the fix.
Sample offset allows for various creative use cases, for example triggering a ghostsnare from a snare, by moving the offset towards the middle of the snare e.g.
