### ISSUE TITLE
keynum to hold/decay is broken after commit 11ee3a9

### ISSUE THREAD

**Issue by mrbumpy409** [davy7125/polyphone#183]
After commit 11ee3a9 (Sound engine more independant), keynum to hold/decay no longer works.

## Steps to Reproduce

1. Load the [attached SoundFont](https://github.com/davy7125/polyphone/files/14656897/keynum.to.hold.test.zip) into Polyphone.
2. Play notes on the first preset—be sure to hold each key down until you no longer hear any sound. As you go up/down from middle C, you should always hear exactly two finger snap sounds. In the high register of the keyboard it will drift into 3 snaps, so ignore that. Presets 000 and 002 test keynum-to-hold for the volume and mod envelopes respectively. They should sound similar to one another. Presets 001 and 003 test keynum-to-decay, and in this case, you will hear the second snap much more faintly or highly filtered.

### Actual Result

High notes play more snaps, and low notes play fewer snaps.

### Expected Result

Notes all across the keyboard should play only two snaps as the hold/decay values are being adjusted based on MIDI key number (except at the top of the keyboard, where the math gets off a bit).

**Comment by davy7125** [comment]
Thanks a lot for this finding and for the soundfont! It's now fixed

**Comment by mrbumpy409** [comment]
Thanks, Davy, for the fix and for your continued work on this editor. It is my lifeblood right now! I'll go ahead and give the update a test. Peace :grin:

**Comment by mrbumpy409** [comment]
I can confirm this bug is indeed fixed!
