### ISSUE TITLE
new pedal issues after fix for #184

### ISSUE THREAD

**Issue by mrbumpy409** [davy7125/polyphone#186]
The fix for #184 created two new issues:

1. Sostenuto pedal behavior is inverted.
2. Both the sustain and sostenuto pedal logic cannot handle continuous-style foot pedals, where smooth values between 0 and 127 are sent. This results in notes released while the pedal is down to continue sustaining after the pedal is released.

I have solved both of these issues in code and will submit a pull request to resolve this ticket.

**Comment by davy7125** [comment]
Great! Your logic was better than mine ;)

I forgot the case where the sustain pedal triggers more than one consecutive "sustain on" signals and I had in mind a sostenuto system for the organ that uses a push button, in which the memory is changed after each press.
