### ISSUE TITLE
xdg mime type integration

### ISSUE THREAD

**Issue by dvzrv** [davy7125/polyphone#19]
For xdg mime type aware Linux environments (when using xdg desktop files), it would be great to provide a mime specification:

In the Arch Linux User Repository (AUR) such a file can be found:
https://aur.archlinux.org/cgit/aur.git/tree/polyphone.mime?h=polyphone

**Comment by davy7125** [comment]
This file is provided in deployment/debian
https://github.com/davy7125/polyphone/blob/master/deployment/debian/polyphone.sharedmimeinfo
Please note that Polyphone can also open sf3 files (the format has been pushed by MuseScore)
