### ISSUE TITLE
Can't download Windows installer, Website transfers at ~10kb/sec and aborts at ~15%

### ISSUE THREAD

**Issue by steviator** [davy7125/polyphone#197]
Impossible to download any files from the polyphone website for at least a week now, it seems like nobody checks basic functionality, at all, ever.

Also, there are no mirrors, as if whoever set up the website was so inept that they thought it would always work flawlessly for everyone, at all times.

**Comment by davy7125** [comment]
The website hosted at www.polyphone-soundfonts.com was aging and I deployed the new website two days ago. Please be patient, I'll fix everything as soon as I can.
Do you confirm that the bug still occurs here  ? https://www.polyphone.io/en/software
If yes, which web browser are you using and from which part of the world are you downloading?

**Comment by davy7125** [comment]
Now fixed
