### ISSUE TITLE
[ENCHANCEMENT] Quality of Life: Show velocity on the on-screen keyboard

### ISSUE THREAD

**Issue by spessasus** [davy7125/polyphone#198]
When you press a key on the piano, it already lights up the key range section for the sample that plays, while the test is greyed out.

I think it would be cool for it to take velocity range into account too. 
Especially with these HQ piano soundfonts which use ton of the same instrument with a different vel range and filter cutoffs (for example Keppy's Steinway Piano).

Currently the entire keyboard lights up, ignoring the velocity range.

**Comment by davy7125** [comment]
I downloaded the piano here: https://musical-artifacts.com/artifacts/543
After opening it I couldn't reproduce what you are describing.

Currently when hitting a key, only the ranges corresponding to that key with the associated velocity are shown. If you see the opposite it would be nice to provide a more precise example.

(side note: I discovered the use of the opcode fil_veltrack when opening the sfz of Keppy's Steinway Piano, I'll implement it)

**Comment by spessasus** [comment]
Hi @davy7125,
thanks for the response.

The soundfont I'm talking about is not sfz, it's sf2:
[Soundfont link](https://www.mediafire.com/file/2e4ezkh83ztpr5r/Keppy%2527s_Steinway_Piano_7.2.sf2/file)
![image](https://github.com/user-attachments/assets/24abd303-ad78-4a81-9d2c-66358d2c8215)

As you can see, the entire keyboard is white and all instrument names turn blue.
(This has fooled me into thinking that all these are playing when I was creating my own soundfont player.)

The correct behavior should only light up "KSPm" with the velocity range 116-117 as the key i pressed has a velocity of 116. Currently, it shows that all keys are playing, which is not true.

I hope this clears things up.

**Comment by davy7125** [comment]
I didn't pay attention to that. Thank you! Now solved
