### ISSUE TITLE
drag&drop d'une SF2/SFZ dans l'arbre provoque une erreur de segmentation

### ISSUE THREAD

**Issue by trebmuh** [davy7125/polyphone#2]
Polyphone 1.8 ici, un glissé/déposé d'une banque SF2 ou SFZ fait planter Polyphone. Lancé à partir d'un terminal, la seule et unique indication donnée est "erreur de segmentation".

**Comment by trebmuh** [comment]
Ça fonctionne nickel à présent.
Merci.

**Comment by trebmuh** [comment]
Une version incluant ce correctif a été reconstruite et placée sur le dépôt de LibraZiK. Merci pour le correctif @davy7125 !

**Comment by davy7125** [comment]
De rien, j'ai également corrigé quelques petits bugs ce soir qui seraient aussi intéressant à prendre en compte

**Comment by trebmuh** [comment]
Super @davy7125 !
C'est empaqueté et placé dans le dépôt de LibraZiK.
J'ai fait un billet, j'espère ne pas avoir dit de bêtise dedans : https://librazik.tuxfamily.org/dotclear/blog/?post/Nouvelle-version-%28encore-une!%29-pour-Polyphone
