### ISSUE TITLE
[Feature Request] Alternative hotkey to navigate through tabs

### ISSUE THREAD

**Issue by audio2000** [davy7125/polyphone#211]
Linux / Debian Based
Version: 2.2.0

I can see that Polyphone offers one of the standard hotkeys for tab navigation
Ctrl+Tab & Ctrl+Shift
Maybe not needed but another common hotkey for applications that contain tabs is
Ctrl+PageUp & Ctrl+PageDown
I was wondering if this would be considered to be added, as long as this is not conflicting with any current actions that I am unaware of.

Thank You

**Comment by audio2000** [comment]
@davy7125 
Just a heads up.
On the following page under the 2.4.0 new release
https://github.com/davy7125/polyphone/releases
you mentioned
`navigation between tabs with Ctrl+Tab and Ctrl+Shift+Tab`
if this is in regards to this request might need to be changed to 
`navigation between tabs with Ctrl+PageUp and Ctrl+PageDown`

Thank you again for adding this

**Comment by davy7125** [comment]
Sorry I forgot this part of your message.
These other shortcuts will be part of the next release but I cannot give a date yet
