### ISSUE TITLE
Asks to save when closing SFZ instruments even if nothing changed

### ISSUE THREAD

**Issue by audio2000** [davy7125/polyphone#212]
Linux / Debian Based
Version: 2.2.0

I apologize if this has already been fixed or if this is by design.
I saw something that mentioned about saving SFZ instruments but it was a Windows user and they mentioned many saving issues regarding not being able to save, that might not be the same as what I am mentioning.

It appears that when you load any SFZ instrument, the tab instantly opens with an *asterisk as if something has been changed.  If you then go to close the tab it asked if you want to save the changes, even though nothing has been changed.
I tested this out with Soundfonts as well but they work fine, only SFZ seem to experience this.

Hopefully this is helpful, again I apologize if this has been corrected in newer version.
Thank You

**Comment by davy7125** [comment]
It was made by design, since importing a sfz editor didn't create yet a soundfont in a dedicated file. But you are right, the correct behavior would be to display the save dialog on close after the first change.
