### ISSUE TITLE
Flatpak and Arch Repos still have 2.3 instead of 2.4

### ISSUE THREAD

**Issue by spessasus** [davy7125/polyphone#214]
As the title says, flatpak and Arch repositories still have outdated versions (2.3.1 and 2.3.0) respectively instead of the latest 2.4 (which I would like to test)

Please update them as running the windows version via wine is buggy as hell. (borderless is broken and there's no sound)

**Comment by davy7125** [comment]
As a developer, I'm "only" updating the sources of Polyphone and have no role in the Arch package system. This issue should be thus addressed to them.
In the meanwhile, a flatpak for Polyphone has been updated to version 2.4
https://flathub.org/apps/com.polyphone_soundfonts.polyphone
(thank you to the Flatpak team!)

**Comment by spessasus** [comment]
Alright, flatpak is fine too. Thanks!
