### ISSUE TITLE
[FEATURE REQUEST] - Option to remove close X from tabs

### ISSUE THREAD

**Issue by audio2000** [davy7125/polyphone#216]
Hello again,
Now that there are a few options to close tabs in Polyphone I was wondering if you think it would be a good setting, to add the ability to hide the close "X"s from each tab.  This is a fairly common setting I have seen in programs that contain tab capabilities, not sure if you think it would be good to add to Polyphone as well?  Could clean up tabs a little if users decides they do not have a need / use the close X's.

(I will not make a separate post about this because I do not think you are going to want to add a setting for this, but while on the same topic maybe a setting to show/hide tab icons as well?  I cannot say if good idea or not, I think I would keep them shown regardless but curious how this would look, a setting for this could be desired by other users.  If interested in this I could make a separate post if you want me to.)

Thank You

**Comment by davy7125** [comment]
I add ticket #218 for better handling this case. I prefer hiding the "x" button only when necessary, no need for an extra option (I try to make the interface as light as possible).
