### ISSUE TITLE
[FEATURE REQUEST] Option to choose category opened to by default

### ISSUE THREAD

**Issue by audio2000** [davy7125/polyphone#217]
In certain situations I feel it could be very beneficial to maybe offer a setting to allow user to choose which "category" is shown in Polyphone by default when opening up an instrument.
By "category" I am referring to the side bar categories.....
GENERAL / SAMPLES / INSTRUMENTS / PRESETS
By default each instrument loads to the GENERAL section but if have a specific function in my that needs to be performed to many instruments over and over, it could be nice to be able to just quickly set Polyphone to open right to that section rather than having to navigate through in each instrument one at a time.
Hopefully this makes sense.
Thank You

**Comment by audio2000** [comment]
Added bonus would be another sub setting for the request made above, which would allow the default category chosen, to automatically have its first layer expanded so can instantly see its contents.
Thank you again

**Comment by davy7125** [comment]
I'm not comfortable with this kind of option. I understand that it might be useful in this specific use case, but knowing that all categories are one click away when opening a soundfont, adding another option doesn't make sense. It's also unlikely that users will know about it.

**Comment by audio2000** [comment]
@davy7125 
I saw that this was now added in `Settings`
Thank you very much for changing your mind about this suggestion.
This works great!
