### ISSUE TITLE
Translate Polyphone to Polish

### ISSUE THREAD

**Issue by spessasus** [davy7125/polyphone#221]
Hi,

I'm a native Polish speaker and I've noticed that Polyphone currently does not have a Polish translation.

I would like to contribute to that if I can.

How can I do that? The .io website shows a link with a translation package, but it's dead...

**Comment by davy7125** [comment]
Hello that would be a great addition! The new polish translation is ready here:
https://www.polyphone.io/en/software/translations

I fixed some links in the documentation but not sure if I found the broken links.

I've seen that your library can be translated too. I'll add French :-)
