### ISSUE TITLE
Loop points getting added to samples when converting .sf2 to .sfz

### ISSUE THREAD

**Issue by susquetzal** [davy7125/polyphone#224]
In Polyphone 2.4 on Linux, when converting an .sf2 soundfont to .sfz, a lot of samples that should be one-shots (such as drums) get exported as looped samples. This happens with all soundfonts I try, and it didn't happen in version 2.3.

**Comment by davy7125** [comment]
I cannot reproduce the problem. Could you please attach a minimal example?

**Comment by davy7125** [comment]
Ok I see that the sample has loop points:
![Capture d’écran du 2024-10-15 09-06-38](https://github.com/user-attachments/assets/5a5089bb-5415-42b8-9e41-f710ca004554)

But my question remains: could you please send a minimal sf2 file, that is exported into a sfz with extra loop points?

**Comment by davy7125** [comment]
Fixed, thank you
