### ISSUE TITLE
Build crashed on start (MacOS / Apple Silicon)

### ISSUE THREAD

**Issue by rubenphilipp** [davy7125/polyphone#228]
Hello,

first of all, thanks for developing this useful piece of software.
Unfortunately, I am not able to use the MacOS binary–neither the one downloaded from your website nor the homebrew-cask. The program immediately crashes after launching the program. 

Here's my system specs:
OS: MacOS 14.7 (23H124)
CPU: Apple M2 Pro

Here's the crash report (ips) for further information:
[polyphone-crash.txt](https://github.com/user-attachments/files/17548303/polyphone-crash.txt)

Let me know if you need further assistance to reproduce the issue.

Best
Ruben

**Comment by thesoundofthesound** [comment]
I'm also getting this same problem when I download the latest version of the [Polyphone app](https://www.polyphone.io/en/software) for macOS. I'm also running an M2 machine, with macOS 13.2.1. 

I thought if I downloaded [Jack](https://jackaudio.org/downloads/) from here it might solve the issue, but it persists.

**Comment by bmFtZQ** [comment]
It seems like a misconfiguration issue as `Jackmp.framework` is included in the app bundle, but based on the error message it is only looking in system locations.

A temporary solution I found was that creating a symbolic link from the framework included with the app bundle to the `/Library/Frameworks` location worked, and the program launched just fine:

```sh
sudo ln -s '/Applications/polyphone.app/Contents/Frameworks/Jackmp.framework' '/Library/Frameworks/Jackmp.framework'
```

**Comment by davy7125** [comment]
Since Jack audio server seems to be obsolete for Mac, it is now removed. This bug is thus fixed for the next Polyphone versions.
