### ISSUE TITLE
Presets velocity layers count column

### ISSUE THREAD

**Issue by audio2000** [davy7125/polyphone#234]
Probably not going to be interested in this one but I figured I would just mention.
I find that it could be helpful information to know, when going through soundfonts, how many layers of velocities they contain.
All soundfonts have to contain at least one of course, but nice to know when soundfonts contain multiple samples for each notes velocity layer(s).
Would be great to see this information in the soundfonts "General" category page but I do not know if other would agree with this.
If not, the only other place I can think of is to maybe add it as a column in the "Presets" category.
All instruments containing samples, would get a "1" by default as mentioned, but if more this column would display the amount of velocity sampler layers that are included in the instrument.

Thank You

**Comment by davy7125** [comment]
The number of layers is specific to an instrument or preset, so this will not be in the general section.
What your describes may be something useful to you but this is too specific.
Instead, please have a look to the range editor:
https://www.polyphone.io/en/documentation/manual/soundfont-editor/editing-pages/instrument-editor#doc_range

You will see at a glance, per instrument or preset, the number of velocity layers.
