### ISSUE TITLE
Allow Export dialog to remember size

### ISSUE THREAD

**Issue by audio2000** [davy7125/polyphone#235]
Currently the Export dialog that is used when converting instruments to different formats, shows a small dialog in the center of the screen.   By default this dialog is programmed to always return to its same default size with each opening.

To me this dialog can be somewhat small and has to be resized each time it is opened.
Would it be considered to maybe be able to remember the adjusted size choosen by user during the last instance it was opened/adjusted? 

If the above is added, would have to make a decision about whether or not to also save the location of the dialog if user decides to move it.  If not, can just have it load up in the center of the Polyphone window as it does by default, but would just be now based on the new size choosen by the user, when centering the dialog.

Thank You

**Comment by davy7125** [comment]
I keep this one :)

**Comment by audio2000** [comment]
That is good, thank you for adding this, I didn't think this one was going to make it in.
