### ISSUE TITLE
regression: using values larger than 16-bit signed integer for sample offset fields is broken again

### ISSUE THREAD

**Issue by mrbumpy409** [davy7125/polyphone#237]
It is no longer possible to store a value smaller than -32768 or larger than 32767 in the following fields:

* Sample start offset
* Sample end offset
* Loop start offset
* Loop end offset

Values larger than 32767 that already exist in an instrument are correctly shown in Polyphone, but any attempts to further edit the values will clamp them to max 32767.

This was a bug that appeared three years ago (bug #141) and then was fixed. Now it is broken again in Polyphone 2.4.1, but I don't know in which version the bug was reintroduced.

**Comment by davy7125** [comment]
I just released the beta of Polyphone 2.5 and will test and fix what you are describing here for the final release.
Thank you for the report
