### ISSUE TITLE
Ctrl+K : retour visuel

### ISSUE THREAD

**Issue by trebmuh** [davy7125/polyphone#3]
Je viens de découvrir qu'en utilisant Ctrl+K, alors le focus est mis sur le clavier virtuel que l'on peut alors piloter avec le clavier alpha-numérique. C'est une super petite fonctionnalité.

Je suggère d'avoir un retour visuel de cette action comme par exemple, un truc du genre:
* ajouter un cadre autour du clavier virtuel qui apparaîtrait après avoir mis le focus dessus,
* mettre un peu de luminosité de fond sur le clavier virtuel lorsque le focus est dessus,
* ...

Je pense que ça aiderai à comprendre que "quelque chose s'est passé lorsque j'ai appuyé sur Ctrl+K".

**Comment by davy7125** [comment]
C'est effectivement une bonne idée ! Toutes les lignes du clavier virtuel prennent maintenant brièvement la couleur de sélection lors de l'appui sur ctrl+K.

**Comment by trebmuh** [comment]
J'ai testé une reconstruction et ça fonctionne bien. Super et merci !
