### ISSUE TITLE
Virtual keyboard reads improper touchpad touches

### ISSUE THREAD

**Issue by apollolux** [davy7125/polyphone#31]
Hello! I'm using Polyphone 1.9 on macOS High Sierra on a MacBook Air. I have "tap to click" disabled system-wide via System Preferences but the virtual keyboard reads touching the touchpad even just to move the mouse cursor as clicking a key with a velocity of 1. This also results in some keys getting stuck as blue, presumably holding those keys down with velocities of 1. There seems to be no reliable, consistent way to unstick these keys other than moving the cursor wildly around the keyboard.

I also hope this issue doesn't affect Windows or Linux systems that use touchpads or similar HIDs (maybe the Lenovo trackpoint nib or even a drawing tablet?), but I wouldn't be surprised if it does.

**Comment by davy7125** [comment]
Thank you for the report, this will be checked!

**Comment by davy7125** [comment]
I am not able to test this feature since I have no special touchpad or touchscreen. I hope someone can check this.
I made a little change in the code but I cannot tell if it's fixed.

**Comment by davy7125** [comment]
Not fixed yet:
https://www.polyphone-soundfonts.com/en/forum/soundfonts-help/395-mac-version
