### ISSUE TITLE
Ability to choose arbitrary sampling rate, without resampling

### ISSUE THREAD

**Issue by jimbo1qaz** [davy7125/polyphone#36]
Soundfonts ripped by vgmtrans often have the wrong sampling rate. I want to be able to change the sampling rate to fix the length and pitch, without resampling the sample data.

Additionally it would be convenient to have arbitrary sampling rates (though I haven't needed anythong not on the list *yet*) .

**Comment by davy7125** [comment]
I prefer not to implement these features for the following reasons:
* the sampling rate bug should be addressed to vgmtrans (https://github.com/vgmtrans/vgmtrans/issues), we are supposed to provide correct samples into Polyphone,
* sample rates are quite standards as we can see here: https://www.csun.edu/~lg48405/sed618/assignments/audio_format.html

The features you propose would make the interface more complex for very particular purposes.
