### ISSUE TITLE
No package libqt5-dev

### ISSUE THREAD

**Issue by Jayman2000** [davy7125/polyphone#38]
In the trunk/README file, it's mentioned that to build Polyphone on a Debian based system, you need to install 'libqt5-dev'. This is misleading since, there is no package called 'libqt5-dev' in any version of Debian or Ubuntu.

**Comment by davy7125** [comment]
Hello this might be "qtbase5-dev"
https://askubuntu.com/questions/508503/whats-the-development-package-for-qt5-in-14-04
I can update the documentation if needed
