### ISSUE TITLE
Download and Installation on Mac fails

### ISSUE THREAD

**Issue by stefan-balke** [davy7125/polyphone#39]
Hi,

I encounter problems with the Downloads on your website.
They fail before finishing...and even if one out of ten finishes,
I get this error message.
![screen shot 2018-10-16 at 11 10 38](https://user-images.githubusercontent.com/7326732/47005582-56d36800-d134-11e8-9770-c5e151466bac.png)

Any ideas on this?

Thanks
Stefan

My system:
![screen shot 2018-10-16 at 11 12 55](https://user-images.githubusercontent.com/7326732/47005633-74a0cd00-d134-11e8-87df-4ce06e6bb851.png)

**Comment by davy7125** [comment]
Sorry for delay. I am now providing .zip files instead of .dmg files, no more issues ;-)
