### ISSUE TITLE
Not able to load samples in VSCO-2-CE

### ISSUE THREAD

**Issue by Wang-Yue** [davy7125/polyphone#4]
The app is able to load sfz files (See https://github.com/sgossner/VSCO-2-CE/tree/SFZ), but not the samples in the VSCO library. 

I'm running it on Mac OS X. 

The other main open source library, virtual playing orchestra, loads fine.

**Comment by davy7125** [comment]
My answer comes late but can you attach an archive containing the sfz + the samples?
