### ISSUE TITLE
FTBS: latest r.a9b1df1 -- qScrollX was not declared in this scope

### ISSUE THREAD

**Issue by Corin-EU** [davy7125/polyphone#5]
On Linux Mint 18.2  (based on Ubuntu 16.04) with

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

libqt4-dev 4:4.8.7+dfsg-5ubuntu2

QT_SELECT=4
export QT_SELECT

qmake

make 
...

      g++ -c -pipe -O2 -pthread -Wall -W -D_REENTRANT -DUSE_LOCAL_QCUSTOMPLOT -DVERSION=1.9 -DFINAL=false -D__LINUX_ALSASEQ__ -D__LITTLE_ENDIAN__ -D__UNIX_JACK__ -D__LINUX_ALSA__ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../trunk -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I/usr/include/jack -I/usr/include/stk -I../trunk/lib/qcustomplot -I../trunk/gui_divers -I../trunk/configuration -I../trunk/pages -Iqcustomplot -I../trunk/ressources -I../trunk/sf2_core -I../trunk/tools -I../trunk/clavier -I../trunk/synthetiseur -I../trunk/synthetiseur/elements -I../trunk/sfark -I../trunk/lib/sf3 -I../trunk -I../trunk/lib/sfarklib -I/usr/include/alsa -IRELEASE/.moc -IRELEASE/.ui -I. -o RELEASE/.obj/graphique.o ../trunk/pages/graphique.cpp
     . ./trunk/pages/graphique.cpp: In member function 'virtual void Graphique::wheelEvent(QWheelEvent*)':
               . ./trunk/pages/graphique.cpp:569:9: 
               error: 'qScrollX' was not declared in this scope
               qScrollX->setValue(qScrollX->value() - 0.05 * event->delta());
               ^
       Makefile:1150: recipe for target 'RELEASE/.obj/graphique.o' failed
       make: *** [RELEASE/.obj/graphique.o] Error 1

**Comment by QuentinFAIDIDE** [comment]
I have exactly the same error on my fedora 25:
Qt Creator 4.1.0
Based on Qt 5.7.1 (GCC 6.3.1 20161221 (Red Hat 6.3.1-1), 64 bit)
