### ISSUE TITLE
Is there documentation for the command-line interface?

### ISSUE THREAD

**Issue by io7m** [davy7125/polyphone#50]
Hello!

I couldn't see anything on https://www.polyphone-soundfonts.com that indicates how to use the command-line interface. I've looked through the source code but can't decipher the command-line options from `options.cpp`.

I'd like to use polyphone to convert between `sfz` and `sf2` formats without needing to open the UI.

**Comment by io7m** [comment]
To answer my own question, at least:

```$ polyphone -1 -i kit.sfz -o kit.sf2```

**Comment by trebmuh** [comment]
If you're running Polyphone on Linux, you can look at the man page (ie: `man polyphone`).

**Comment by io7m** [comment]
> If you're running Polyphone on Linux, you can look at the man page (ie: man polyphone).

My distribution (Arch) doesn't seem to include the manual page, and I can't find the manual page sources in this repository.

**Comment by trebmuh** [comment]
There is one in the source. Look [here](https://github.com/davy7125/polyphone/tree/master/deployment/debian).

**Comment by io7m** [comment]
Thanks!

**Comment by trebmuh** [comment]
@io7m you're welcome

@davy7125 : it'd be great if the manpage (EN and FR) could be installed for everyone (ie: not only Debian)

**Comment by davy7125** [comment]
@trebmuh thank you for your help here :-)
I am not maintaining the Arch linux package so all requests regarding it should be addressed to the packagers: https://aur.archlinux.org/packages/polyphone
(there is a "Submit Request" link)

**Comment by trebmuh** [comment]
@davy7125 I meant that if you could add a generic installation of the manpage in the install step, it'd be great, then it wouldn't depend on every distro, but would be done once for all.
