### ISSUE TITLE
compatibility with qcustomplot > 2

### ISSUE THREAD

**Issue by dvzrv** [davy7125/polyphone#56]
The current codebase is not compatible to qcustomplot > 2 ([due to code simplification](https://www.qcustomplot.com/release/2.0.1/changelog.txt)). It would be great to refactor the codebase to be able to build against a more recent version (on Linux and potentially other OSes - which became apparent in #45 ).

**Comment by mercuriete** [comment]
I hit to this problem yesterday.
In Gentoo there is only qcustomplot 2.0 -> https://packages.gentoo.org/packages/dev-libs/qcustomplot

I had to create a custom gentoo package of qcustomplot-1.3.2 and that worked.

Nice project :) thanks.

**Comment by mercuriete** [comment]
Nice! thank you for the effort.
I will try to recompile it.

**Comment by dvzrv** [comment]
@davy7125 thanks a lot! If you tag a new release, I can start distributing this right away!

**Comment by davy7125** [comment]
I have no roadmap for a version 2.1 but I'll try to solve most of the open tickets. Depending of my effectiveness it can take some months !

**Comment by dvzrv** [comment]
@davy7125 Yeah, no hurry there :)
I can try to apply your commit, if it applies cleanly on top of the latest stable version.

Else: A bugfix release is always welcomed ;-)

**Comment by dvzrv** [comment]
It works, when applying https://github.com/davy7125/polyphone/commit/a8223e1 beforehand! :)
