### ISSUE TITLE
add travis Continous integration

### ISSUE THREAD

**Issue by mercuriete** [davy7125/polyphone#57]
I would like to contribute to this project doing continous integration but I failed.

You can see my job there:

https://github.com/mercuriete/polyphone/blob/stable/.travis.yml

my problem is nullptr is not defined in c++ standars < 11 and I dont know how to tell qmake to use another g++.

If you can give some advise to continue in this task... I will continue.

Good project :)

**Comment by davy7125** [comment]
Could you please try to add this line in polyphone.pro file:
`QMAKE_CXXFLAGS += -std=c++11`

And if it's not enough, add this one also:
`CONFIG += c++11`

**Comment by davy7125** [comment]
I added the file you created in the main depository, with the additional "C++11" in the .pro file. The result of Travis is:

```
make: *** No rule to make target 'generated_files/sfarkextractor1.o', needed by 'bin/polyphone'.  Stop.
make: *** Waiting for unfinished jobs....
The command "cd sources && qmake polyphone.pro QMAKE_CC=gcc-7 QMAKE_CXX=gcc-7 && make -j$(nproc)" exited with 2.
```

It may be linked to #54 . I'm investigating...

**Comment by mercuriete** [comment]
@davy7125 
ohhh nice!

I will check it your approach :)
