### ISSUE TITLE
polyphone v1.8 built from source -- coredumps with realloc(): invalid pointer: 0x0831b1dc 

### ISSUE THREAD

**Issue by Corin-EU** [davy7125/polyphone#6]
On Linux Mint 18.2 (based on Ubuntu 16.04) with

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

libqt4-dev 4:4.8.7+dfsg-5ubuntu2

QT_SELECT=4
export QT_SELECT

with polyphone v1.8 built from source immediately crashes on execution.

/usr/local/bin/polyphone
*** Error in `/usr/local/bin/polyphone': realloc(): invalid pointer: 0x0831b1dc ***

[backtrace-polyphone.txt](https://github.com/davy7125/polyphone/files/1227115/backtrace-polyphone.txt)

What I do not understant is why polyphone is showing links to Qt5 libraries when built with Qt4, unless these libraries are supposed to be backwards compatible with Qt4.

    ldd /usr/local/bin/polyphone  | grep Qt | sort
          libQt5Core.so.5 => /usr/lib/i386-linux-gnu/libQt5Core.so.5 (0xb5047000)
          libQt5Gui.so.5 => /usr/lib/i386-linux-gnu/libQt5Gui.so.5 (0xb550b000)
          libQt5PrintSupport.so.5 => /usr/lib/i386-linux-gnu/libQt5PrintSupport.so.5 (0xb61d3000)
          libQt5Widgets.so.5 => /usr/lib/i386-linux-gnu/libQt5Widgets.so.5 (0xb5a93000)
          libQtCore.so.4 => /usr/lib/i386-linux-gnu/libQtCore.so.4 (0xb6621000)
          libQtGui.so.4 => /usr/lib/i386-linux-gnu/libQtGui.so.4 (0xb6927000)
          libQtSvg.so.4 => /usr/lib/i386-linux-gnu/libQtSvg.so.4 (0xb743e000)

Is it time for polyphone to move to qt5?

**Comment by fcahoon** [comment]
I had the same problem on Debian unstable but `qmake -qt5 && make` produced an executable that works fine. I think that the README should be edited to remove the references to building with QT4 and all will be fine. (I'll leave that to someone who is more familiar with QT.)

**Comment by jimbo1qaz** [comment]
I hit this issue myself, still waiting for the README to be fixed...

**Comment by forrcaho** [comment]
I'll likely submit a pull request during Hacktober if no one else fixes this. I'd _really_ rather someone with more of a clue would do it; the sum total of my knowledge of the subject being in my comment above.

**Comment by jimbo1qaz** [comment]
Actually I already submitted a pr, editing the documentation to install qt5 and run qmake -qt=5.
