### ISSUE TITLE
The project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [davy7125/polyphone#62]
Please see how the Arch linux port installs it manually: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/polyphone
This should be done by your make file.

**Comment by davy7125** [comment]
I'm using qmake and I would need some help to understand what should be done.
There is also a new problem, linked to #55: I removed the directory deployment and now I don't know where to upload it. Should I create another repository for the deployment?

**Comment by trebmuh** [comment]
> Should I create another repository for the deployment?

Maybe in a specific branch of this repo? Some devs are doing so. Just mentioning.

**Comment by davy7125** [comment]
There is now a branch "deployment" that contains some stuff that I use myself for creating releases (Mac, Debian, Windows). Regarding this ticket I don't what should be done.
If this is a work for a specific distribution => please provide a pull request with the proposed enhancement

**Comment by yurivict** [comment]
qmake-based projects are able to install files that they build.
Please install what Arch linux installs in the function ```package()``` in the link in my OP.
All UNIX-like systems should have the same file hierarchy installed.
