### ISSUE TITLE
Please use $$PREFIX instead of /usr in your .pro file

### ISSUE THREAD

**Issue by yurivict** [davy7125/polyphone#63]
Example: https://github.com/davy7125/polyphone/blob/master/sources/polyphone.pro#L69

Some systems use ```/usr/local``` for packages to install. PREFIX variable should contain the correct location.

**Comment by davy7125** [comment]
Could you please tell me what I should write instead of the following?
```
    isEmpty(PREFIX) {
        PREFIX = /usr/local
    }
    TARGET.path = $$PREFIX/
```
PREFIX  is set to /usr/local if nothing has been specified when calling qmake, this is just a default configuration.

**Comment by yurivict** [comment]
@davy7125 This should remain because this sets the initial value of PREFIX when it isn't set.

All other mentions of ```/usr``` should become ```$$PREFIX```.

For example:
```
-    INCLUDEPATH += /usr/include/qcustomplot
+    INCLUDEPATH += $$PREFIX/include/qcustomplot
```

**Comment by davy7125** [comment]
If $$PREFIX is /usr/local, we would have the following?
`
-    INCLUDEPATH += /usr/include/qcustomplot
+    INCLUDEPATH += $$PREFIX/../include/qcustomplot
`
