### ISSUE TITLE
missing translation source files

### ISSUE THREAD

**Issue by trebmuh** [davy7125/polyphone#71]
Salut @davy7125,
il semble qu'il manque les sources pour les traductions dans https://github.com/davy7125/polyphone/tree/master/sources/resources/translations où ne se trouvent actuellement que les fichiers compilés *.qm .

**Comment by trebmuh** [comment]
Mes excuses, elles sont dans le répertoire sources/ .

**Comment by davy7125** [comment]
Le choix du répertoire "sources" est discutable, mais étant donné que la commande "lupdate polyphone.pro" génère les fichiers *.ts à côté du .pro, j'ai gardé cette configuration.

**Comment by trebmuh** [comment]
pas de soucis de mon côté
