### ISSUE TITLE
Invalid default value for sfModTransOper

### ISSUE THREAD

**Issue by mawe42** [davy7125/polyphone#73]
Version: Polyphone 2.1.0 running on Ubuntu 18.04

When adding a new modulator via the "+" button to a global or local preset or instrument zone, editing any fields apart from the transform value and saving the soundfont as SF2, the sfModTransOper for that modulator is `1` in the written file.

If you change the transform to "absolute" and then back to "no operation" and save the file again, the sfModTransOper is correctly written as 0. Looks like the initial values for the transform select box is missing the special "0 or 2" treatment applied in all other places.

This drove me insane for a a while, because FluidSynth silently sets the amount of all modulators with invalid transform to 0. And I kept wondering why my modulator doesn't work... ;-)

**Comment by davy7125** [comment]
Thank you for this! Nice finding.
