### ISSUE TITLE
XDG integration missing

### ISSUE THREAD

**Issue by dvzrv** [davy7125/polyphone#78]
Currently, the release tarball doesn't include any XDG desktop integration anymore.
It seems it was moved to the [deployment branch](https://github.com/davy7125/polyphone/tree/deployment/debian).

Please note, that e.g. `polyphone.desktop`, `polyphone.1`, `polyphone.fr.1`, `polyphone.sharedmimeinfo` (which should really be called `polyphone.xml`) are all Linux specific (not exclusively Debian) and should be included in the release tarball.
Similar to e.g. `polyphone.plist` (which is macOS specific) they can just live directly in the sources directory for example.

If you intend to provide a separate `debian/` package build directory (on a branch or wherever), that's fine, but the current situation is actually very suboptimal for all Linux distributions (as these integrational files now have to be gotten from a specific commit on a branch).

**Comment by davy7125** [comment]
It's been indeed moved in the deployment branch so that everything is clean in master. The deployment branch is intended to be used primarily by me for the package I'm providing in the Polyphone website. Anything related to other Linux distributions will be the burden for packagers, I don't want to deal with this. I can of course accept pull request solving specific cases.

**Comment by dvzrv** [comment]
I don't quite understand the attitude here.
The man pages for example can even be used on macOS *and* Linux (*and* on BSDs). All the aforementioned files are (Linux) distribution agnostic and should be part of the repository.
What benefit does it have (especially when the files I mentioned require change or get an update) to not have them in a release tarball? This way noone will offer pull requests towards these files and it will lead to more fragmented results in the end (also because tracking the latest changes of those files is much harder). I'd argue, that the files are part of the project, not of deployment.

**Comment by davy7125** [comment]
Thank you for the fix. Sorry if I didn't want to deal with this case... On the one hand I have been asked to clean the repository, on the other hand files or missing so I'm a bit lost in the middle of this.

**Comment by dvzrv** [comment]
On 2019-10-07 23:21:46 (-0700), Davy Triponney wrote:
> Thank you for the fix. Sorry if I didn't want to deal with this
> case... On the one hand I have been asked to clean the repository, on
> the other hand files or missing so I'm a bit lost in the middle of
> this.

I understand and I'm sorry, if I was part of that! ;-)

-- 
https://sleepmap.de
