### ISSUE TITLE
[Feature Request] Flatpack or Snap Package ( or both )

### ISSUE THREAD

**Issue by zicklag** [davy7125/polyphone#80]
It would be awesome to have Polyphone on [Snapcraft.io](https://snapcraft.io) or [Flathub.org](https://flathub.org). It could also very well get this awesome tool some more exposure to a larger audience.

Both Snaps and Flatpaks are linux distro agnostic which means you can support tons of Linux distro's with one or two builds. Having an officially maintained Snap would mean that Linux users could automatically get updates to the application without having to do anything, and having a Flatpak would mean that users could install the app without having to have administrator access to the machine.

If we were to pick one, I would say do the snap first, but it would still be cool to have both.

This is something that I might find time to work on, but no guarantees.

**Comment by davy7125** [comment]
This is a good suggestion, help is of course welcome if you already made such a package!

**Comment by zicklag** [comment]
I haven't made one yet, but I plan on making some snaps for Open Source projects that I use if I can find the time. Could you assign this to me so I don't forget.

**Comment by hfiguiere** [comment]
For the flatpak, see https://github.com/flathub/flathub/pull/1414

Needs some ironing out still.

**Comment by davy7125** [comment]
Should the content of this repository be included somewhere here?
https://github.com/flathub/com.polyphone_soundfonts.polyphone

What job is needed or remains in this ticket?

**Comment by hfiguiere** [comment]
> Should the content of this repository be included somewhere here?
> https://github.com/flathub/com.polyphone_soundfonts.polyphone

Where it is is where it used to build the flatpak on flathub. You could have a manifest in your source tree, but it wouldn't be used by flatpak anyway, and would need to be adapted to work standalone as it relies on a shared-module git submodule (unless you add it too, and also now that the appdata file is in the repository.

> What job is needed or remains in this ticket?

Adding a link to the flathub page (https://flathub.org/apps/details/com.polyphone_soundfonts.polyphone) from the download page could be nice, but otherwise I think the issue can be closed.

**Comment by hfiguiere** [comment]
Unless you consider providing a Snap is also needed (since it's part of the original request)

**Comment by davy7125** [comment]
Perfect, thank you very much for your contribution and for the link :-)
I added an external link in this page:
https://www.polyphone-soundfonts.com/download
