### ISSUE TITLE
Mac OS X: Service exited with abnormal code: 1

### ISSUE THREAD

**Issue by MaxPayne86** [davy7125/polyphone#83]
Hi, I've tried to install polyphone on a friend's Mac, syslog is giving this error, application doesn't run

com.apple.xpc.launchd[1] (fr.polyphone.Polyphone.149152[1242]): Service exited with abnormal code: 1

any idea?

**Comment by davy7125** [comment]
Maybe same than
https://www.polyphone-soundfonts.com/en/forum/support-bug-reports/409-bug-application-does-not-startt-osx-el-capitan

**Comment by pereshaped** [comment]
Doesn't run on Yosemite or Maverick either

**Comment by davy7125** [comment]
I close this bug since a new installer will be made for the new version to come.
Older versions will not be updated
