### ISSUE TITLE
Can't compile in Mac Osx 

### ISSUE THREAD

**Issue by zhouhao27** [davy7125/polyphone#92]
Got the following error:
```
/Users/xxx/Public/test/polyphone/sources/core/utils.cpp:28: error: 'openssl/rsa.h' file not found

/Users/xxx/Public/test/polyphone/sources/context/audiodevice.cpp:32: error: 'jack.h' file not found
#include "jack.h"
         ^~~~~~~~
```

My Xcode version: 11.2.1
OSX：10.15.2
Polyphone：2.2

**Comment by hfiguiere** [comment]
PR #100 should fix this

**Comment by davy7125** [comment]
@zhouhao27 I fixed the location of the jack header and I think you didn't copied / pasted the lib_mac folder next to the source folder as described here:
https://www.polyphone-soundfonts.com/documentation/en/development/building-polyphone-for-mac-os-x
