### ISSUE TITLE
XDG mimetypes DB not build properly

### ISSUE THREAD

**Issue by redtide** [davy7125/polyphone#94]
The original mimetype definitions installed by polyphone results in a wrong xml after a `update-mime-database` command. This might be due by different definitions (sf2, sf3, sfArk and sfz) under the same x-soundfont type, resulting only with the comment of the last defined one (sfArk):

```xml
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="audio/x-soundfont">
  <!--Created automatically by update-mime-database. DO NOT EDIT!-->
  <glob pattern="*.sf2"/>
  <glob pattern="*.sfz"/>
  <glob pattern="*.sf3"/>
  <comment>SoundFont archive sfArk</comment>
  <glob pattern="*.sfArk"/>
</mime-type>
```
Could it be to use different mime types, e.g.: x-soundfont, x-audio-sfz (which AFAIK is not a soundfont), x-soundfont-v3 and x-soundfont-ark a solution?

**Comment by jpcima** [comment]
Yes that's a problem which I confirm on side.
Moreover, it's preferable if SFZ gets its own MIME type that not only Polyphone and graphcial editors can open, because text editors should be candidates as well.

**Comment by mirabilos** [comment]
Care to propose a fix?

**Comment by redtide** [comment]
@mirabilos I think I proposed already one but, before doing a PR, I would like to have some feedback/POV from the author.

**Comment by mirabilos** [comment]
redtide dixit:

>@mirabilos I think I proposed already one but, before doing a PR, I
>@would like to have some feedback/POV from the author.

OK, granted that sounds sensible ☺

I was a little hoping you had something already, which I could
add to my Debian package as local patch…

**Comment by davy7125** [comment]
I agree with the fact that an sfz file should be considered first as a text file, that can then be opened by Polyphone.
Since I accepted pull request #113, can I close this ticket?

Also, in Italian should it be **Editor di soundfont** or something else with soundfont in the plural form? Like "Editor de soundfonts"?

**Comment by redtide** [comment]
Sorry, I forgot about this (and/or if there was a reason to keep it open).

Usually in Italian, untranslated English terms are used to be singular e.g. `Anna utilizza degli editor per modificare i suoi file di testo` (Anna uses editors to edit her text files): not "editors", nor "files". so **Editor di soundfont** is correct.

**Comment by davy7125** [comment]
Thank you for the details. I'll change it
